import Head from 'next/head'
import Image from 'next/image'

export default function Home () {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='mx-auto relative mt-24 px-4 max-w-3xl'>
        <section id='intro'>
          <div className='mb-4 flex justify-between md:flex-row-reverse md:justify-end md:items-center md:gap-x-4'>
            <div>
              <h1 className='font-outfit text-h1 text-ink'>Rob McLoughlin</h1>
              <span>Product Design @ Chupi &amp; Human</span>
            </div>
            <div className='-mt-4 md:mt-0'>
              <Image alt='My face' src='/profile.png' width={64} height={64} />
            </div>
          </div>
          <summary className='block md:flex md:gap-x-6'>
            <p className='mb-4 md:w-1/2'>
              I am a designer and developer from Dublin with 5 years experience
              defining problems and solving them through data-driven designs and
              good infastructure.
            </p>
            <div className='md:w-1/2'>
              <h2 className='mb-2 font-bold md:hidden'>Experience</h2>
              <ul>
                <li>
                  BSc in{' '}
                  <a
                    className='underline'
                    target='_blank'
                    rel='noreferrer'
                    href='https://iadt.ie/courses/applied-psychology/'
                  >
                    Applied Psychology
                  </a>{' '}
                  (1.1)
                </li>
                <li>
                  MSc in{' '}
                  <a
                    className='underline'
                    target='_blank'
                    rel='noreferrer'
                    href='https://iadt.ie/courses/user-experience-design/'
                  >
                    UX Design
                  </a>{' '}
                  (1.1)
                </li>
                <li>5 Years Experience</li>
              </ul>
            </div>
          </summary>
        </section>
      </main>
    </div>
  )
}
