import Head from 'next/head'
import Image from 'next/image'
import { Degree, Clock } from '@/components/Icons'
import fs from 'fs'
import path from 'path'
import matter from 'gray-matter'
import ProjectCard from '@/components/ProjectCard'

export default function Home ({ projects }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='mx-auto relative mt-24 px-4 max-w-3xl'>
        <section id='intro'>
          <div className='mb-4 flex justify-between md:flex-row-reverse md:justify-end md:items-center md:gap-x-4'>
            <div>
              <h1 className='font-outfit text-h1 text-ink'>Rob McLoughlin</h1>
              <span>Product Design @ Chupi &amp; Human</span>
            </div>
            <div className='-mt-4 md:mt-0'>
              <Image alt='My face' src='/profile.png' width={64} height={64} />
            </div>
          </div>
          <summary className='block md:flex md:gap-x-6'>
            <p className='mb-4 md:w-1/2'>
              I am a designer and developer from Dublin with 5 years experience
              defining problems and solving them through data-driven designs and
              good infastructure.
            </p>
            <div className='md:w-1/2'>
              <h2 className='mb-2 font-bold md:hidden'>Experience</h2>
              <ul>
                <li className='flex gap-x-2 items-center mb-2'>
                  <Degree />
                  BSc in{' '}
                  <a
                    className='underline'
                    target='_blank'
                    rel='noreferrer'
                    href='https://iadt.ie/courses/applied-psychology/'
                  >
                    Applied Psychology
                  </a>{' '}
                  (1.1)
                </li>
                <li className='flex gap-x-2 items-center mb-2'>
                  <Degree />
                  MSc in{''}
                  <a
                    className='underline'
                    target='_blank'
                    rel='noreferrer'
                    href='https://iadt.ie/courses/user-experience-design/'
                  >
                    UX Design
                  </a>{' '}
                  (1.1)
                </li>
                <li className='flex gap-x-2 items-center mb-2'>
                  <Clock />5 Years Experience
                </li>
              </ul>
            </div>
          </summary>
        </section>

        <section id='projects' className='py-12'>
          <h2 className='mb-4 font-outfit test-ink text-h1'>Recent Projects</h2>
          <p>
            I am not permitted to re-display work so I will link to the live
            project and write up my process on them!
          </p>
          <ul>
            {projects.map(({ slug, frontMatter: project }) => {
              return (
                <li key={slug}>
                  <ProjectCard project={project} slug={slug} />
                </li>
              )
            })}
          </ul>
        </section>
      </main>
    </div>
  )
}

export const getStaticProps = async () => {
  const files = fs.readdirSync(path.join('projects'))

  const projects = files.map(filename => {
    const markdownWithMeta = fs.readFileSync(
      path.join('projects', filename),
      'utf-8'
    )
    const { data: frontMatter } = matter(markdownWithMeta)

    return {
      frontMatter,
      slug: filename.split('.')[0]
    }
  })

  const ordered = projects.sort(p => p.frontMatter.order).slice(0, 2)

  return {
    props: {
      projects: ordered
    }
  }
}
